sudo: required
services:
  - docker

before_install:
  - docker build -t jfourdachon/nuxt-test -f ./front/Dockerfile.dev ./front
  # to run others test
  #- docker build jfourdachon/api-test -f ./api.Dockerfile.dec ./api

script:
  - docker run -e CI=true jfourdachon/nuxt-quizz npm run test

after_success:
  - docker nuild -t jfourdachon/multi-front ./front
  - docker nuild -t jfourdachon/multi-nginx ./nginx
  - docker nuild -t jfourdachon/multi-api ./api
  - docker nuild -t jfourdachon/multi-worker ./worker

  # Login to docker CLI
  # Set docker credentials in travis.com -> project settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  # Take those images and push them to docker hub
  - docker push jfourdachon/multi-front
  - docker push jfourdachon/multi-nginx
  - docker push jfourdachon/multi-api
  - docker push jfourdachon/multi-worker

  