version: '3'
services:
  redis:
    image: 'redis:latest'
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - COMPLEX_DATABASE
  front:
    build: 
      dockerfile: Dockerfile
      context: ./front
    command:
      "npm run start"
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  webhooks:
    build:
      dockerfile: Dockerfile
      context: ./webhooks
  # DISABLED FOR HOT RELAD IN DEV
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes: 
     - /etc/certifs:/etc/nginx/ssl
    depends_on:
      - api
      - front
