version: '3'
services:
  redis:
    image: 'redis:latest'
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./api:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - COMPLEX_DATABASE
  front:
    build: 
      dockerfile: Dockerfile.dev
      context: ./front
    volumes: 
      - /app/node_modules
      - ./front:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  # DISABLED FOR HOT RELAD IN DEV
  webhooks:
    build:
      dockerfile: Dockerfile.dev
      context: ./webhooks
    volumes: 
      - /app/node_modules
      - ./webhooks:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - api
      - front
      - webhooks
