version: '3'
services:
  redis:
    image: 'redis:latest'
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - COMPLEX_DATABASE